# Generated by Django 4.2.16 on 2024-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('datetime_created', models.TimeField(auto_now_add=True)),
                ('datetime_modified', models.TimeField(auto_now=True)),
            ],
        ),
    ]
